apiVersion: apps/v1
kind: Deployment
metadata:
  name: toktik-uf
  labels:
    app: toktik-uf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: toktik-uf
  template:
    metadata:
      labels:
        app: toktik-uf
    spec:
      containers:
      - name: toktik-uf
        image: ghcr.io/kun99-p2/auth-frontend/toktik-uf:latest
        ports:
        - containerPort: 3000
      imagePullSecrets:
      - name: ghcr-secret
---
kind: Service
apiVersion: v1
metadata:
  name: toktik-uf
spec:
  selector:
    app: toktik-uf
  type:  ClusterIP
  ports:
  - name:  http
    port:  80
    targetPort:  3000