apiVersion: apps/v1
kind: Deployment
metadata:
  name: chunker
spec:
  replicas: 3
  selector:
    matchLabels:
      app: chunker
  template:
    metadata:
      labels:
        app: chunker
    spec:
      containers:
      - name: chunker
        image: ghcr.io/kun99-p2/chunker/toktik-chunker:latest
      - name: redis-server
        image: redis:latest
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  selector:
    app: chunker
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379