apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: toktik-ingress
spec:
  rules:
  - host: localhost
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: toktik-uf
              port:
                number: 80
        # - path: /2
        #   pathType: ImplementationSpecific
        #   backend:
        #     service:
        #       name: toktik-vf
        #       port:
        #         number: 80
        # - path: /3
        #   pathType: ImplementationSpecific
        #   backend:
        #     service:
        #       name: toktik-pf
        #       port:
        #         number: 80
