apiVersion: v1
type: kubernetes.io/dockerconfigjson
kind: Secret
metadata:
  name: toktik-secret
  labels:
    app: toktik-secret
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJnaXRodWIuY29tIjoge30KCX0sCgkiY3JlZHNTdG9yZSI6ICJkZXNrdG9wIiwKCSJjdXJyZW50Q29udGV4dCI6ICJkZWZhdWx0IiwKCSJwbHVnaW5zIjogewoJCSIteC1jbGktaGludHMiOiB7CgkJCSJlbmFibGVkIjogInRydWUiCgkJfQoJfQp9